language: python

sudo: true
fast_finish: true

# python:
#   - "3.4"
#   - "3.5"
#   - "3.6"

matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install Cython
  - pip install -r requirements.txt
  - pip install .

script:
  - nosetests

after_success:
  - coveralls

branches:
  only:
    - master
    - develop

notifications:
  slack: tradologics:HcnS6XusfcuS02waQPCG18oc
  webhooks:
    urls:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
